Document: bashy
Title: Debian bashy Manual
Author: <insert document author here>
Abstract: This manual describes what bashy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bashy/bashy.sgml.gz

Format: postscript
Files: /usr/share/doc/bashy/bashy.ps.gz

Format: text
Files: /usr/share/doc/bashy/bashy.text.gz

Format: HTML
Index: /usr/share/doc/bashy/html/index.html
Files: /usr/share/doc/bashy/html/*.html
